### ISSUE TITLE
Update to follow Decidim

### ISSUE THREAD

**Issue by Waateur** [alabs/decidim-module-calendar#16]
Hi,
Will this module be updated to follow decidim update ? 
current Stable is 0.20 and the calendar module cannot be installed with this version.

**Comment by paranoix** [comment]
Well, we haven't tested it yet for this version of Decidim, so we'll review it and give you some information. Kind regards.

**Comment by mrcasals** [comment]
Same issue here @mijailr... Could you at least relax the version requirement?

Thanks!

**Comment by mrcasals** [comment]
Also pinging @andreslucena 🙏

**Comment by mrcasals** [comment]
Thanks @andreslucena! ❤️

**Comment by andreslucena** [comment]
Thank you @mrcasals for the report and even the PR ;) 
@Waateur you should be able to check it with: 

`gem "decidim-calendar", github: "alabs/decidim-module-calendar"`

As on aLabs we're having some issues on accessing our rubygems account

**Comment by andreslucena** [comment]
It's already published this new version on rubygems also
